name: eye_planner
description: "EyePlanner is an innovative mobile application developed in Flutter, 
  designed to facilitate booking appointments with opticians. With a user-friendly and 
  intuitive interface, users can quickly find opticians, check their availability, and 
  book time slots in just a few clicks."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/fonts/google_fonts/
   - assets/fonts/google_fonts/OFL.txt
   - assets/Lottie/anim1.json
   - assets/images/optician.jpeg
   - assets/images/colorLogo.png
   - assets/images/googleLogo.png
   - assets/images/checkLogo.png
   - assets/images/profileImage.png
   - assets/images/calendarRemoveBg.png
   - assets/images/personage.png
  

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/google_fonts/Lora-Bold.ttf
          weight: 700
        - asset: assets/fonts/google_fonts/Lora-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/google_fonts/Lora-Italic.ttf
          style: italic
        - asset: assets/fonts/google_fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/google_fonts/Lora-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/google_fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/google_fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/google_fonts/Lora-SemiBoldItalic.ttf
          weight: 600
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
